### ISSUE TITLE
Can initial level of nodes be retrieved and set programmatically?

### ISSUE THREAD

**Issue by jonrkarr** [GINsim/GINsim-python#18]
Is there a way to programmatically get and set the initial value of each node?

I don't see a way to do this. 

#6 appears to confirm this cannot be get and set.
> We may still need a way to set this initial value.

**Comment by aurelien-naldi** [comment]
As mentioned in #19, bioLQM does not maintain an initial level for the components. The initial level is mostly used to run simulations and can be defined programatically there. If (hopefully when) we add a way to associate the initial level to a model, we will provide an API to access and modify it
