### ISSUE TITLE
biolqm: Invalid fixpoint returned

### ISSUE THREAD

**Issue by pauleve** [GINsim/GINsim-python#2]
When computing fixpoint on model http://ginsim.org/sites/default/files/Traynard_MultiLevel_MamCC_Apr2016.zginml
biolqm returns a strange fixpoint with a value -1 for CycA, as illustrated in the following notebook:
https://gist.github.com/pauleve/e31dddff15e82b770a4f32de99b24bc4

**Comment by aurelien-naldi** [comment]
It is not an error but I can see why it is confusing! As the computation of fixpoints is using decision diagrams, the extracted results are paths in the diagram: -1 means that this variable is not used in the path, the state is stable no matter its value. The example represents two fixpoints, matching the result obtained with pint.
It is easy to extract all fully-defined fixpoints, I can update the code to do this by default, proposing to get this compressed result as an option instead.

**Comment by aurelien-naldi** [comment]
With the last commit, bioLQM unfolds such patterns by default, a command-line switch allows to keep them
