### ISSUE TITLE
Automatic layout for regulatory graphs (was: Converted bioLQM model graph image is clipped)

### ISSUE THREAD

**Issue by stairs** [GINsim/GINsim-python#5]
After converting bioLQM model to GINsim I get just a cut version of the whole graph in my Jupiter notebook:
![download](https://user-images.githubusercontent.com/6586371/72151386-60d02f00-33a8-11ea-9906-27c8cb312750.png)
When uploading a model from GINsim repository rendering works fine. I guess it might be a layout absence issue but I'm not sure how to pass right params via the wrapper.
Here is a standard code snippet I used:
```
lrg = biolqm.to_ginsim(lqm)
ginsim.show(lrg)
```
Any insight would be appreciated. Thanks in advance!

**Comment by pauleve** [comment]
I'm not sure bioLQM or GINsim implement automatic layout (ping @aurelien-naldi)
If you are dealing with a Boolean network, you can give a try to `minibn` to display its influence graph:
```
bn = biolqm.to_minibn(lqm)
bn.influence_graph()
```
I've not implemented the multi-valued case yet..

**Comment by stairs** [comment]
Thanks for the advice! Looks great for simple graph representation!
However, I'm still interested in displaying fixpoints as well.

**Comment by aurelien-naldi** [comment]
Indeed, GINsim only handles graphs for which a layout already exists.
How does minibn generate the layout? If it can export it as a map, we could then add a method to import in GINsim to display fixpoints

**Comment by pauleve** [comment]
using graphviz (so not so scalable..) - but sure, we can make a function which outputs a map from each node to a position. Is that all you need, or do you also need position/paths for edges?
How do you see it: a hacky insertion in the ginml file by the python interface, or you want to add a parameter to biolqm to specify the position map?

**Comment by aurelien-naldi** [comment]
I have recently added a "ModelLayout" class to bioLQM to cleanup support for the SBML layout extension. I would like to expose this to add the layout to an already loaded bioLQM model: it would let us side-load several layouts if we want and allow to use other layout algorithms later on.

**Comment by pauleve** [comment]
I just pushed a generic function `layout_graph` in `colomoto.helpers` module:
```python
from colomoto.helpers import layout_graph
layout = layout_graph(bn.influence_graph())
```
a second argument can be passed to specify the graphviz algorithm (e.g., "fdp" or "sfdp" for large graphs).

`layout` contains informations on node positions and edges b-splines:
```python
{'nodes': {'GATA3': {'x': 6.9802, 'y': 5.5488, 'width': 1.1013, 'height': 0.5},
  'IFNb': {'x': 13.509, 'y': 11.893, 'width': 0.81243, 'height': 0.5},
  ...
 'edges': [{'tail': 'GATA3',
   'head': 'IL4',
   'bspline': [(7.0239, 5.8012),
    (7.0924, 6.1961),
    (7.2254, 6.9635),
    (7.3065, 7.4317)]},
...
}
```

Edit: I implemented a rough `influence_graph` for multi-valued networks as well

**Comment by aurelien-naldi** [comment]
That's more than enough, thanks!

For now the simple layout store in bioLQM only handles node positions, extending it to edges paths should not be a problem. Node size and style will be more problematic as GINsim internal styling system is not so stable.

I updated biolqm.to_ginsim to retain the layout and added a python wrapper to load the generated layout map.

`biolqm.add_layout(model, layout)` should work in the next release. I will also call it from `biolqm.load(filename, layout=layout)`.

**Comment by pauleve** [comment]
Great :+1: 
Note that we should be able to skip the minibn conversion part by converting the (java) regulatory graph to a networkx graph object and give it to layout_graph. I'll open an issue later to track this optimization.

**Comment by pauleve** [comment]
I've added the automatic layout in biolqm, without going through minibn. It is performed automatically by the `to_ginsim` method if there is no layout, so it should be transparent now.
Once the ginsim anaconda package is updated I'll create a new release of colomoto-jupyter  then of GINsim-python, and then the changes will be live on the docker image :-)

**Comment by pauleve** [comment]
I've updated conda packages for ginsim and colomoto-jupyter and made a quick tutorial of this layout feature: https://gist.github.com/pauleve/0bea6fd14e741c4795ef3fda2c13c245
Let me know what you think, and if it looks fine to you, we can release the current GINsim-python module and update the docker image.

**Comment by aurelien-naldi** [comment]
Yes, it looks fine thanks!

**Comment by pauleve** [comment]
This is now included in the image tagged `next`, which will be persistently tagged during the night.
