### ISSUE TITLE
`ginsim_setup.py` isn't bundled with the PyPI distribution

### ISSUE THREAD

**Issue by jonrkarr** [GINsim/GINsim-python#7]
The installation instructions for installing from PyPI in the README cannot followed by `ginsim_setup.py` isn't bundled with the PyPI distribution.

**Comment by pauleve** [comment]
Thanks for noticing this. This will be included in the next release.
The current installation workflow outside conda suffers from many drawbacks. The solution you suggest in #11 could definitely help.
