### ISSUE TITLE
Installation from PyPI also requires adding the `GINSim` executable to the system path

### ISSUE THREAD

**Issue by jonrkarr** [GINsim/GINsim-python#8]

**Comment by pauleve** [comment]
This should be handled by the `ginsim_setup` which installs the program in a specific location (`~/.local/share/colomoto/bin`) if it does not find it in the `PATH`.

**Comment by jonrkarr** [comment]
That wasn't the case for me. This might depend on permissions and/or environment.

Another option would be to store the GINSim executable in `site-packages` and keep track of the path with `pkg_resources.resource_filename`.

**Comment by jonrkarr** [comment]
`ginsim_setup.py` didn't setup the paths correctly in the `python:3.9-slim-buster` Docker image either.

**Comment by pauleve** [comment]
This should be fixed now. I'll make a new release after a couple of more tests. Thanks for reporting this!

**Comment by pauleve** [comment]
Fixed in 0.4.4
